"use client";

import { useParams, useSearchParams } from "next/navigation";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Suspense, useCallback, useEffect, useRef, useState } from "react";
import { MarkdownEditor } from "@/components/editor/markdown-editor";
import { Preview } from "@/components/editor/preview";
import { useStreaming } from "@/hooks/use-streaming";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

type ContentRow = {
  id: string;
  title: string;
  body: string;
  bodyHtml: string | null;
  status: string;
  keywordId: string | null;
  tone: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoTags: string | null;
  sourceUrls: string | null;
  scheduledAt: string | null;
  scheduledPlatform: string | null;
  createdAt: string;
  updatedAt: string;
};

const TONE_OPTIONS = [
  { value: "informative", label: "정보 전달형" },
  { value: "conversational", label: "대화체" },
  { value: "expert", label: "전문가" },
];

export default function EditorPage() {
  return (
    <Suspense>
      <EditorContent />
    </Suspense>
  );
}

function EditorContent() {
  const { id } = useParams<{ id: string }>();
  const searchParams = useSearchParams();
  const keyword = searchParams.get("keyword") || "";

  const [title, setTitle] = useState("");
  const [tone, setTone] = useState("informative");
  const [saveStatus, setSaveStatus] = useState<"saved" | "saving" | "unsaved">(
    "saved"
  );
  const [activeTab, setActiveTab] = useState<"editor" | "preview">("editor");
  const [showSeo, setShowSeo] = useState(false);
  const [publishResult, setPublishResult] = useState<{
    ok?: boolean;
    url?: string;
    error?: string;
  } | null>(null);
  const [autoPublish, setAutoPublish] = useState<"blogger" | "naver" | null>(null);
  const queryClient = useQueryClient();

  const saveTimerRef = useRef<ReturnType<typeof setTimeout>>(undefined);
  const handleAutoPublish = useCallback(
    (text: string) => {
      if (autoPublish && text.length > 100) {
        // 생성 완료 후 자동 발행
        setTimeout(() => {
          handlePublishRef.current?.(autoPublish);
        }, 500);
      }
    },
    [autoPublish]
  );
  const streaming = useStreaming({ onComplete: handleAutoPublish });
  const handlePublishRef = useRef<((platform: "blogger" | "naver") => void) | null>(null);

  // 콘텐츠 조회
  const { data: content, refetch } = useQuery<ContentRow>({
    queryKey: ["content", id],
    queryFn: async () => {
      const res = await fetch(`/api/content/${id}`);
      if (!res.ok) throw new Error("Failed to fetch content");
      return res.json();
    },
  });

  // 초기 데이터 로드
  useEffect(() => {
    if (content) {
      setTitle(content.title);
      if (content.tone) setTone(content.tone);
      if (content.body && !streaming.text) {
        streaming.setText(content.body);
      }
    }
  }, [content]); // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-save (1초 debounce)
  const save = useCallback(
    async (body: string, newTitle?: string) => {
      setSaveStatus("saving");
      try {
        await fetch(`/api/content/${id}`, {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            body,
            title: newTitle || title,
          }),
        });
        setSaveStatus("saved");
      } catch {
        setSaveStatus("unsaved");
        toast.error("저장에 실패했습니다");
      }
    },
    [id, title]
  );

  const handleBodyChange = useCallback(
    (newBody: string) => {
      streaming.setText(newBody);
      setSaveStatus("unsaved");

      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
      saveTimerRef.current = setTimeout(() => save(newBody), 1000);
    },
    [save, streaming]
  );

  const handleTitleChange = useCallback(
    (newTitle: string) => {
      setTitle(newTitle);
      setSaveStatus("unsaved");

      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
      saveTimerRef.current = setTimeout(
        () => save(streaming.text, newTitle),
        1000
      );
    },
    [save, streaming.text]
  );

  // AI 생성 시작
  const handleGenerate = useCallback(() => {
    const kw = keyword || title;
    if (!kw) return;
    streaming.start({
      contentId: id,
      keyword: kw,
      tone,
    });
  }, [id, keyword, title, tone, streaming]);

  // 키워드 파라미터로 진입 시 자동 생성
  const autoGeneratedRef = useRef(false);
  useEffect(() => {
    if (keyword && content && !content.body && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      streaming.start({
        contentId: id,
        keyword,
        tone,
      });
    }
  }, [keyword, content]); // eslint-disable-line react-hooks/exhaustive-deps

  // 발행
  const handlePublish = useCallback(
    async (platform: "blogger" | "naver") => {
      setAutoPublish(null); // 자동 발행 플래그 리셋
      setPublishResult(null);
      try {
        // 먼저 현재 내용 저장
        await save(streaming.text);

        const res = await fetch(`/api/publish/${platform}`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ contentId: id }),
        });
        const data = await res.json();
        if (!res.ok) {
          setPublishResult({ error: data.error });
          toast.error(`발행 실패: ${data.error}`);
        } else {
          setPublishResult({ ok: true, url: data.externalUrl });
          toast.success("발행 완료!", {
            action: data.externalUrl
              ? { label: "블로그에서 보기", onClick: () => window.open(data.externalUrl, "_blank") }
              : undefined,
          });
          refetch();
          queryClient.invalidateQueries({ queryKey: ["contents"] });
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : "Publish failed";
        setPublishResult({ error: msg });
        toast.error(`발행 실패: ${msg}`);
      }
    },
    [id, streaming.text, save, refetch, queryClient]
  );

  // ref로 handlePublish를 onComplete 콜백에서 접근
  handlePublishRef.current = handlePublish;

  const saveStatusLabel = {
    saved: "저장됨",
    saving: "저장 중...",
    unsaved: "변경사항 있음",
  };

  return (
    <div className="flex flex-col h-full gap-4">
      {/* 상단 바 */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex-1">
          <Input
            value={title}
            onChange={(e) => handleTitleChange(e.target.value)}
            placeholder="제목을 입력하세요"
            className="text-lg font-semibold border-0 border-b rounded-none px-0 focus-visible:ring-0"
          />
        </div>
        <div className="flex items-center gap-2">
          <select
            value={tone}
            onChange={(e) => setTone(e.target.value)}
            className="text-sm border rounded-md px-2 py-1.5 bg-background"
          >
            {TONE_OPTIONS.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>

          <Badge variant={saveStatus === "saved" ? "secondary" : "outline"}>
            {saveStatusLabel[saveStatus]}
          </Badge>

          {streaming.isStreaming ? (
            <Button variant="destructive" size="sm" onClick={streaming.stop}>
              생성 중단
            </Button>
          ) : (
            <Button size="sm" onClick={handleGenerate}>
              AI 생성
            </Button>
          )}

          <ImageSearch
            keyword={keyword || title}
            onInsert={(markdown) => {
              const newText = streaming.text + "\n\n" + markdown;
              handleBodyChange(newText);
            }}
          />
        </div>
      </div>

      {streaming.isStreaming && (
        <Badge variant="default" className="w-fit">
          AI가 글을 생성하고 있습니다...
        </Badge>
      )}

      {streaming.error && (
        <div className="text-sm text-destructive bg-destructive/10 p-3 rounded-md flex items-center justify-between">
          <span>AI 생성 실패: {streaming.error}</span>
          <Button variant="outline" size="sm" onClick={handleGenerate}>
            재시도
          </Button>
        </div>
      )}

      {/* 에디터 + 미리보기 */}
      {/* 모바일: 탭 전환 */}
      <div className="md:hidden flex gap-1 border-b">
        <button
          onClick={() => setActiveTab("editor")}
          className={`px-3 py-1.5 text-sm ${activeTab === "editor" ? "border-b-2 border-primary font-medium" : "text-muted-foreground"}`}
        >
          에디터
        </button>
        <button
          onClick={() => setActiveTab("preview")}
          className={`px-3 py-1.5 text-sm ${activeTab === "preview" ? "border-b-2 border-primary font-medium" : "text-muted-foreground"}`}
        >
          미리보기
        </button>
      </div>

      <div className="flex-1 flex gap-4 min-h-0">
        {/* 데스크톱: 좌 70% 에디터, 우 30% 미리보기 */}
        <div
          className={`flex-[7] min-h-0 ${activeTab === "preview" ? "hidden md:block" : ""}`}
        >
          <MarkdownEditor
            value={streaming.text}
            onChange={handleBodyChange}
            disabled={streaming.isStreaming}
            placeholder={
              streaming.text
                ? undefined
                : "키워드를 선택하거나 직접 글을 작성하세요"
            }
          />
        </div>
        <div
          className={`flex-[3] min-h-0 border rounded-md overflow-auto ${activeTab === "editor" ? "hidden md:block" : ""}`}
        >
          <Preview markdown={streaming.text} />
        </div>
      </div>

      {/* SEO 섹션 (접힘) */}
      <div className="border rounded-md">
        <button
          onClick={() => setShowSeo(!showSeo)}
          className="w-full px-4 py-2 text-sm text-left font-medium flex items-center justify-between"
        >
          <span>SEO 메타데이터</span>
          <span className="text-muted-foreground">
            {showSeo ? "접기" : "펼치기"}
          </span>
        </button>
        {showSeo && content && (
          <div className="px-4 pb-4 space-y-2 text-sm">
            <div>
              <label className="text-muted-foreground">SEO 제목</label>
              <p>{content.seoTitle || "AI 생성 완료 후 자동 생성됩니다"}</p>
            </div>
            <div>
              <label className="text-muted-foreground">SEO 설명</label>
              <p>
                {content.seoDescription || "AI 생성 완료 후 자동 생성됩니다"}
              </p>
            </div>
            <div>
              <label className="text-muted-foreground">태그</label>
              <div className="flex flex-wrap gap-1 mt-1">
                {content.seoTags
                  ? JSON.parse(content.seoTags).map(
                      (tag: string, i: number) => (
                        <Badge key={i} variant="outline">
                          {tag}
                        </Badge>
                      )
                    )
                  : "AI 생성 완료 후 자동 생성됩니다"}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* 발행 섹션 */}
      <div className="flex items-center gap-2 pt-2 border-t flex-wrap">
        <span className="text-sm font-medium">발행:</span>
        <Button
          size="sm"
          onClick={() => handlePublish("blogger")}
          disabled={streaming.isStreaming || !streaming.text}
        >
          Blogger
        </Button>
        <Button
          size="sm"
          variant="outline"
          onClick={() => handlePublish("naver")}
          disabled={streaming.isStreaming || !streaming.text}
        >
          네이버
        </Button>
        {content?.status === "published" && (
          <Badge variant="default">발행됨</Badge>
        )}

        <span className="text-muted-foreground mx-1">|</span>
        <label className="flex items-center gap-1.5 text-xs text-muted-foreground cursor-pointer">
          <input
            type="checkbox"
            checked={autoPublish === "blogger"}
            onChange={(e) => setAutoPublish(e.target.checked ? "blogger" : null)}
            className="rounded"
          />
          생성 후 Blogger 자동 발행
        </label>
        <label className="flex items-center gap-1.5 text-xs text-muted-foreground cursor-pointer">
          <input
            type="checkbox"
            checked={autoPublish === "naver"}
            onChange={(e) => setAutoPublish(e.target.checked ? "naver" : null)}
            className="rounded"
          />
          생성 후 네이버 자동 발행
        </label>
        {autoPublish && streaming.isStreaming && (
          <Badge variant="outline" className="text-xs">
            생성 완료 시 {autoPublish === "blogger" ? "Blogger" : "네이버"}에 자동 발행됩니다
          </Badge>
        )}
      </div>

      {/* 예약 발행 */}
      <SchedulePublish
        contentId={id}
        scheduledAt={content?.scheduledAt || null}
        scheduledPlatform={content?.scheduledPlatform || null}
        disabled={streaming.isStreaming || !streaming.text}
        onScheduled={() => refetch()}
      />

      {publishResult && (
        <div
          className={`text-sm p-3 rounded-md ${
            publishResult.ok
              ? "bg-primary/10 text-primary"
              : "bg-destructive/10 text-destructive"
          }`}
        >
          {publishResult.ok ? (
            <>
              발행 완료!{" "}
              {publishResult.url && (
                <a
                  href={publishResult.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline"
                >
                  블로그에서 보기
                </a>
              )}
            </>
          ) : (
            <>발행 실패: {publishResult.error}</>
          )}
        </div>
      )}
    </div>
  );
}

// 예약 발행 컴포넌트
function SchedulePublish({
  contentId,
  scheduledAt,
  scheduledPlatform,
  disabled,
  onScheduled,
}: {
  contentId: string;
  scheduledAt: string | null;
  scheduledPlatform: string | null;
  disabled: boolean;
  onScheduled: () => void;
}) {
  const [date, setDate] = useState("");
  const [time, setTime] = useState("");
  const [platform, setPlatform] = useState<"blogger" | "naver">("blogger");
  const [loading, setLoading] = useState(false);

  const handleSchedule = async () => {
    if (!date || !time) {
      toast.error("날짜와 시간을 선택해주세요");
      return;
    }
    const scheduledAt = new Date(`${date}T${time}`).toISOString();
    setLoading(true);
    try {
      const res = await fetch("/api/publish/schedule", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contentId, scheduledAt, platform }),
      });
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error);
      } else {
        toast.success(`${platform === "blogger" ? "Blogger" : "네이버"}에 ${date} ${time} 발행 예약됨`);
        onScheduled();
      }
    } catch {
      toast.error("예약 발행 설정에 실패했습니다");
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = async () => {
    setLoading(true);
    try {
      await fetch("/api/publish/schedule", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contentId }),
      });
      toast.success("예약이 취소되었습니다");
      onScheduled();
    } catch {
      toast.error("예약 취소에 실패했습니다");
    } finally {
      setLoading(false);
    }
  };

  if (scheduledAt) {
    const dt = new Date(scheduledAt);
    return (
      <div className="flex items-center gap-2 text-sm bg-muted p-3 rounded-md">
        <Badge variant="outline">예약됨</Badge>
        <span>
          {dt.toLocaleDateString("ko-KR")} {dt.toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}
          {" "}— {scheduledPlatform === "blogger" ? "Blogger" : "네이버"}
        </span>
        <Button size="sm" variant="ghost" onClick={handleCancel} disabled={loading}>
          취소
        </Button>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-2 flex-wrap text-sm">
      <span className="text-muted-foreground">예약 발행:</span>
      <input
        type="date"
        value={date}
        onChange={(e) => setDate(e.target.value)}
        className="border rounded px-2 py-1 text-sm bg-background"
        min={new Date().toISOString().split("T")[0]}
      />
      <input
        type="time"
        value={time}
        onChange={(e) => setTime(e.target.value)}
        className="border rounded px-2 py-1 text-sm bg-background"
      />
      <select
        value={platform}
        onChange={(e) => setPlatform(e.target.value as "blogger" | "naver")}
        className="border rounded px-2 py-1 text-sm bg-background"
      >
        <option value="blogger">Blogger</option>
        <option value="naver">네이버</option>
      </select>
      <Button size="sm" variant="outline" onClick={handleSchedule} disabled={disabled || loading || !date || !time}>
        {loading ? "설정 중..." : "예약"}
      </Button>
    </div>
  );
}

// 이미지 검색 + 삽입 컴포넌트
function ImageSearch({
  keyword,
  onInsert,
}: {
  keyword: string;
  onInsert: (markdown: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [images, setImages] = useState<
    { id: string; url: string; thumb: string; alt: string; credit: string }[]
  >([]);
  const [loading, setLoading] = useState(false);

  const handleSearch = async () => {
    const q = query || keyword;
    if (!q) return;
    setLoading(true);
    try {
      const res = await fetch(`/api/images?q=${encodeURIComponent(q)}`);
      const data = await res.json();
      setImages(data.images || []);
      if (data.images?.length === 0) {
        toast.error(data.message || "이미지를 찾지 못했습니다");
      }
    } catch {
      toast.error("이미지 검색에 실패했습니다");
    } finally {
      setLoading(false);
    }
  };

  const handleInsert = (img: { url: string; alt: string; credit: string }) => {
    const md = `![${img.alt}](${img.url})\n*${img.credit}*`;
    onInsert(md);
    setOpen(false);
    toast.success("이미지가 삽입되었습니다");
  };

  if (!open) {
    return (
      <Button size="sm" variant="outline" onClick={() => { setOpen(true); setQuery(keyword); }}>
        이미지
      </Button>
    );
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
      <div className="bg-background rounded-lg shadow-xl w-full max-w-2xl max-h-[80vh] flex flex-col">
        <div className="p-4 border-b flex items-center gap-2">
          <Input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="이미지 검색..."
            className="flex-1"
            onKeyDown={(e) => e.key === "Enter" && handleSearch()}
          />
          <Button size="sm" onClick={handleSearch} disabled={loading}>
            {loading ? "검색 중..." : "검색"}
          </Button>
          <Button size="sm" variant="ghost" onClick={() => setOpen(false)}>
            닫기
          </Button>
        </div>
        <div className="p-4 overflow-auto flex-1">
          {images.length === 0 ? (
            <p className="text-sm text-muted-foreground text-center py-8">
              키워드를 입력하고 검색하세요
            </p>
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
              {images.map((img) => (
                <div
                  key={img.id}
                  className="cursor-pointer rounded-md overflow-hidden border hover:border-primary transition-colors"
                  onClick={() => handleInsert(img)}
                >
                  <img
                    src={img.thumb}
                    alt={img.alt}
                    className="w-full h-28 object-cover"
                    loading="lazy"
                  />
                  <p className="text-xs text-muted-foreground p-1 truncate">
                    {img.alt}
                  </p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
