"use client";

import { useParams, useSearchParams } from "next/navigation";
import { useQuery, useMutation } from "@tanstack/react-query";
import { useCallback, useEffect, useRef, useState } from "react";
import { MarkdownEditor } from "@/components/editor/markdown-editor";
import { Preview } from "@/components/editor/preview";
import { useStreaming } from "@/hooks/use-streaming";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type ContentRow = {
  id: string;
  title: string;
  body: string;
  bodyHtml: string | null;
  status: string;
  keywordId: string | null;
  tone: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoTags: string | null;
  sourceUrls: string | null;
  createdAt: string;
  updatedAt: string;
};

const TONE_OPTIONS = [
  { value: "informative", label: "정보 전달형" },
  { value: "conversational", label: "대화체" },
  { value: "expert", label: "전문가" },
];

export default function EditorPage() {
  const { id } = useParams<{ id: string }>();
  const searchParams = useSearchParams();
  const keyword = searchParams.get("keyword") || "";

  const [title, setTitle] = useState("");
  const [tone, setTone] = useState("informative");
  const [saveStatus, setSaveStatus] = useState<"saved" | "saving" | "unsaved">(
    "saved"
  );
  const [activeTab, setActiveTab] = useState<"editor" | "preview">("editor");
  const [showSeo, setShowSeo] = useState(false);

  const saveTimerRef = useRef<ReturnType<typeof setTimeout>>(undefined);
  const streaming = useStreaming();

  // 콘텐츠 조회
  const { data: content, refetch } = useQuery<ContentRow>({
    queryKey: ["content", id],
    queryFn: async () => {
      const res = await fetch(`/api/content/${id}`);
      if (!res.ok) throw new Error("Failed to fetch content");
      return res.json();
    },
  });

  // 초기 데이터 로드
  useEffect(() => {
    if (content) {
      setTitle(content.title);
      if (content.tone) setTone(content.tone);
      if (content.body && !streaming.text) {
        streaming.setText(content.body);
      }
    }
  }, [content]); // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-save (1초 debounce)
  const save = useCallback(
    async (body: string, newTitle?: string) => {
      setSaveStatus("saving");
      try {
        await fetch(`/api/content/${id}`, {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            body,
            title: newTitle || title,
          }),
        });
        setSaveStatus("saved");
      } catch {
        setSaveStatus("unsaved");
      }
    },
    [id, title]
  );

  const handleBodyChange = useCallback(
    (newBody: string) => {
      streaming.setText(newBody);
      setSaveStatus("unsaved");

      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
      saveTimerRef.current = setTimeout(() => save(newBody), 1000);
    },
    [save, streaming]
  );

  const handleTitleChange = useCallback(
    (newTitle: string) => {
      setTitle(newTitle);
      setSaveStatus("unsaved");

      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
      saveTimerRef.current = setTimeout(
        () => save(streaming.text, newTitle),
        1000
      );
    },
    [save, streaming.text]
  );

  // AI 생성 시작
  const handleGenerate = useCallback(() => {
    const kw = keyword || title;
    if (!kw) return;
    streaming.start({
      contentId: id,
      keyword: kw,
      tone,
    });
  }, [id, keyword, title, tone, streaming]);

  // 키워드 파라미터로 진입 시 자동 생성
  const autoGeneratedRef = useRef(false);
  useEffect(() => {
    if (keyword && content && !content.body && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      streaming.start({
        contentId: id,
        keyword,
        tone,
      });
    }
  }, [keyword, content]); // eslint-disable-line react-hooks/exhaustive-deps

  const saveStatusLabel = {
    saved: "저장됨",
    saving: "저장 중...",
    unsaved: "변경사항 있음",
  };

  return (
    <div className="flex flex-col h-full gap-4">
      {/* 상단 바 */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex-1">
          <Input
            value={title}
            onChange={(e) => handleTitleChange(e.target.value)}
            placeholder="제목을 입력하세요"
            className="text-lg font-semibold border-0 border-b rounded-none px-0 focus-visible:ring-0"
          />
        </div>
        <div className="flex items-center gap-2">
          <select
            value={tone}
            onChange={(e) => setTone(e.target.value)}
            className="text-sm border rounded-md px-2 py-1.5 bg-background"
          >
            {TONE_OPTIONS.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>

          <Badge variant={saveStatus === "saved" ? "secondary" : "outline"}>
            {saveStatusLabel[saveStatus]}
          </Badge>

          {streaming.isStreaming ? (
            <Button variant="destructive" size="sm" onClick={streaming.stop}>
              생성 중단
            </Button>
          ) : (
            <Button size="sm" onClick={handleGenerate}>
              AI 생성
            </Button>
          )}
        </div>
      </div>

      {streaming.isStreaming && (
        <Badge variant="default" className="w-fit">
          AI가 글을 생성하고 있습니다...
        </Badge>
      )}

      {streaming.error && (
        <div className="text-sm text-destructive bg-destructive/10 p-3 rounded-md flex items-center justify-between">
          <span>AI 생성 실패: {streaming.error}</span>
          <Button variant="outline" size="sm" onClick={handleGenerate}>
            재시도
          </Button>
        </div>
      )}

      {/* 에디터 + 미리보기 */}
      {/* 모바일: 탭 전환 */}
      <div className="md:hidden flex gap-1 border-b">
        <button
          onClick={() => setActiveTab("editor")}
          className={`px-3 py-1.5 text-sm ${activeTab === "editor" ? "border-b-2 border-primary font-medium" : "text-muted-foreground"}`}
        >
          에디터
        </button>
        <button
          onClick={() => setActiveTab("preview")}
          className={`px-3 py-1.5 text-sm ${activeTab === "preview" ? "border-b-2 border-primary font-medium" : "text-muted-foreground"}`}
        >
          미리보기
        </button>
      </div>

      <div className="flex-1 flex gap-4 min-h-0">
        {/* 데스크톱: 좌 70% 에디터, 우 30% 미리보기 */}
        <div
          className={`flex-[7] min-h-0 ${activeTab === "preview" ? "hidden md:block" : ""}`}
        >
          <MarkdownEditor
            value={streaming.text}
            onChange={handleBodyChange}
            disabled={streaming.isStreaming}
            placeholder={
              streaming.text
                ? undefined
                : "키워드를 선택하거나 직접 글을 작성하세요"
            }
          />
        </div>
        <div
          className={`flex-[3] min-h-0 border rounded-md overflow-auto ${activeTab === "editor" ? "hidden md:block" : ""}`}
        >
          <Preview markdown={streaming.text} />
        </div>
      </div>

      {/* SEO 섹션 (접힘) */}
      <div className="border rounded-md">
        <button
          onClick={() => setShowSeo(!showSeo)}
          className="w-full px-4 py-2 text-sm text-left font-medium flex items-center justify-between"
        >
          <span>SEO 메타데이터</span>
          <span className="text-muted-foreground">
            {showSeo ? "접기" : "펼치기"}
          </span>
        </button>
        {showSeo && content && (
          <div className="px-4 pb-4 space-y-2 text-sm">
            <div>
              <label className="text-muted-foreground">SEO 제목</label>
              <p>{content.seoTitle || "AI 생성 완료 후 자동 생성됩니다"}</p>
            </div>
            <div>
              <label className="text-muted-foreground">SEO 설명</label>
              <p>
                {content.seoDescription || "AI 생성 완료 후 자동 생성됩니다"}
              </p>
            </div>
            <div>
              <label className="text-muted-foreground">태그</label>
              <div className="flex flex-wrap gap-1 mt-1">
                {content.seoTags
                  ? JSON.parse(content.seoTags).map(
                      (tag: string, i: number) => (
                        <Badge key={i} variant="outline">
                          {tag}
                        </Badge>
                      )
                    )
                  : "AI 생성 완료 후 자동 생성됩니다"}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
